title: Jonathan Hoium (hoium04)
description: Tech Ops Engineer @dotloop
author:
  name: Jonathan Hoium
  nickname: hoium04
hostname: hoium.me # used to determine if google analytics should be triggered
url: https://hoium.me # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /:title/

# stuff for jekyll-seo-tag
social:
  name: Jonathan Hoium
  links:
    - https://www.facebook.com/hoium04
    - https://www.instagram.com/hoium04
    - https://www.linkedin.com/in/hoium04
    - https://github.com/hoium
    - https://gitlab.com/hoium

links:
  - name: facebook
    url: https://www.facebook.com/hoium04
    class: fa-facebook-square
  - name: instagram
    url: https://www.instagram.com/hoium04/
    class: fa-instagram
  - name: linkedin
    url: https://www.linkedin.com/in/hoium04
    class: fa-linkedin-square
  - name: github
    url: https://github.com/hoium
    class: fa-github-alt
  - name: gitlab
    url: https://gitlab.com/hoium
    class: fa-gitlab

# additional stuff
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
